"""API keys: the first credential in this product that is not a Supabase-
issued JWT (ADR-0009 §4). Owner-issued, shown once, and looked up by hash
before any org or user identity is known at all.

The ADR names argon2id for `key_hash`; this uses SHA-256 instead, and that is
a deliberate substitution, not an oversight. Argon2id's whole purpose is
making an *offline* brute force of a *low-entropy* secret a human chose (a
password) expensive. An API key is not that: it is `secrets.token_urlsafe`
output, 256 bits of real entropy generated by the machine — brute-forcing a
SHA-256 hash of it is infeasible regardless of hash speed. What Argon2 would
actually cost here is real: its whole design salts identical inputs to
different outputs, so it cannot be looked up by an index at all — every
authenticated trust-API request would mean iterating and verifying against
every issued key in the database instead of one indexed lookup, a real
availability problem for a read path other systems are meant to depend on.
SHA-256 keeps the property the ADR actually states ("the raw key is shown
once and never stored") without that cost.
"""

from __future__ import annotations

import hashlib
import secrets
import uuid
from typing import Annotated, Any

from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy import text

from lumen_api.auth.dependencies import Identity, require_role
from lumen_api.db.session import service_session, user_session
from lumen_api.errors import NotFound

router = APIRouter(prefix="/v1/api-keys", tags=["api-keys"])

_KEY_PREFIX = "lum_"


def _generate_key() -> str:
    return _KEY_PREFIX + secrets.token_urlsafe(32)


def _hash_key(raw: str) -> str:
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


class ApiKeyCreate(BaseModel):
    name: str
    scope: str  # "read:glossary" | "read:certification"


@router.post("")
async def create_api_key(
    body: ApiKeyCreate,
    # Same bar as ADR-0004's plan_change and this ADR's own framing
    # ("owner-only, shown once"): this issues a credential another system
    # can use against tenant data, not a data-quality decision.
    identity: Annotated[Identity, Depends(require_role("owner"))],
) -> dict[str, Any]:
    raw = _generate_key()
    async with user_session(identity.user_id) as db:
        row = (
            await db.execute(
                text(
                    "insert into public.api_keys (org_id, name, key_hash, key_prefix, "
                    "                              scope, created_by) "
                    "values (:org, :name, :hash, :prefix, cast(:scope as public.api_key_scope), :user) "
                    "returning id, name, key_prefix, scope, created_at"
                ),
                {
                    "org": identity.org_id,
                    "name": body.name,
                    "hash": _hash_key(raw),
                    "prefix": raw[:12],
                    "scope": body.scope,
                    "user": identity.user_id,
                },
            )
        ).mappings().first()

    # The only response, ever, that carries the raw key — nothing this
    # product does afterward can show it again, including this same endpoint
    # called a second time.
    return {**{k: v for k, v in dict(row).items() if k != "id"}, "id": str(row["id"]), "key": raw}


@router.get("")
async def list_api_keys(
    identity: Annotated[Identity, Depends(require_role("owner"))],
) -> dict[str, Any]:
    async with user_session(identity.user_id) as db:
        rows = (
            await db.execute(
                text(
                    "select id, name, key_prefix, scope, created_at, revoked_at "
                    "from public.api_keys order by created_at desc"
                )
            )
        ).mappings().all()
    return {"keys": [dict(row) for row in rows]}


@router.delete("/{key_id}")
async def revoke_api_key(
    key_id: uuid.UUID,
    identity: Annotated[Identity, Depends(require_role("owner"))],
) -> dict[str, Any]:
    async with user_session(identity.user_id) as db:
        result = await db.execute(
            text(
                "update public.api_keys set revoked_at = now() "
                "where id = :id and revoked_at is null"
            ),
            {"id": key_id},
        )
    if result.rowcount == 0:
        raise NotFound("No active API key with that id")
    return {"id": str(key_id), "revoked": True}


class ApiKeyAuth:
    """Resolved from a valid, unrevoked key: enough to open the same
    RLS-scoped session pattern every other tenant read uses (`db/session.py`),
    keyed off the key's org rather than a person's own sign-in."""

    __slots__ = ("key_id", "org_id", "scope", "user_id")

    def __init__(self, key_id: uuid.UUID, org_id: uuid.UUID, scope: str, user_id: uuid.UUID) -> None:
        self.key_id = key_id
        self.org_id = org_id
        self.scope = scope
        self.user_id = user_id


async def authenticate(raw_key: str, required_scope: str) -> ApiKeyAuth | None:
    """Hash, look up, check scope and revocation, and resolve a live member
    of the key's org to run the actual read as. `service_session()` is only
    for this lookup, before any identity exists to key an RLS session by —
    every tenant row this resolves to read still goes through the normal
    `user_session()` an authenticated member's own request would use.
    """
    if not raw_key.startswith(_KEY_PREFIX):
        return None

    async with service_session() as db:
        row = (
            await db.execute(
                text(
                    "select id, org_id, scope, revoked_at from public.api_keys where key_hash = :hash"
                ),
                {"hash": _hash_key(raw_key)},
            )
        ).mappings().first()
        if row is None or row["revoked_at"] is not None or str(row["scope"]) != required_scope:
            return None

        # Any current member resolves is_org_member(org_id) to true — read
        # access is org-uniform, so which one does not matter semantically.
        # Preferring the owner, then earliest, avoids the key silently
        # breaking if whoever happened to issue it later leaves the org.
        member = (
            await db.execute(
                text(
                    "select user_id from public.memberships where org_id = :org "
                    "order by (role = 'owner') desc, created_at asc limit 1"
                ),
                {"org": row["org_id"]},
            )
        ).mappings().first()
    if member is None:
        # The org that issued this key has nobody left to act as — an
        # abandoned workspace, not a valid credential anymore.
        return None

    return ApiKeyAuth(
        key_id=row["id"], org_id=row["org_id"], scope=str(row["scope"]), user_id=member["user_id"]
    )
