"""Factory — domain `business`."""
from __future__ import annotations
from typing import Any
from core.abstract_factory import RegistryFactory

class BusinessStatisticsFactory(RegistryFactory[str, Any]):
    pass

def _register() -> None:
    from statistics.business.backends import pandas_impl as p
    from statistics.business.backends import polars_impl as pl
    from statistics.business.backends import spark_impl as sp

    BusinessStatisticsFactory.register("period_churn_calculator", "pandas", p.PeriodChurnCalculatorPandas)
    BusinessStatisticsFactory.register("period_churn_calculator", "polars", pl.PeriodChurnCalculatorPolars)
    BusinessStatisticsFactory.register("period_churn_calculator", "spark", sp.PeriodChurnCalculatorSpark)
    BusinessStatisticsFactory.register("churn_from_events_calculator", "pandas", p.ChurnFromEventsCalculatorPandas)
    BusinessStatisticsFactory.register("churn_from_events_calculator", "polars", pl.ChurnFromEventsCalculatorPolars)
    BusinessStatisticsFactory.register("churn_from_events_calculator", "spark", sp.ChurnFromEventsCalculatorSpark)
    BusinessStatisticsFactory.register("churn_rate_calculator", "pandas", p.ChurnRateCalculatorPandas)
    BusinessStatisticsFactory.register("churn_rate_calculator", "polars", pl.ChurnRateCalculatorPolars)
    BusinessStatisticsFactory.register("churn_rate_calculator", "spark", sp.ChurnRateCalculatorSpark)
    BusinessStatisticsFactory.register("funnel_metrics_computer", "pandas", p.FunnelMetricsComputerPandas)
    BusinessStatisticsFactory.register("funnel_metrics_computer", "polars", pl.FunnelMetricsComputerPolars)
    BusinessStatisticsFactory.register("funnel_metrics_computer", "spark", sp.FunnelMetricsComputerSpark)
    BusinessStatisticsFactory.register("funnel_from_events_builder", "pandas", p.FunnelFromEventsBuilderPandas)
    BusinessStatisticsFactory.register("funnel_from_events_builder", "polars", pl.FunnelFromEventsBuilderPolars)
    BusinessStatisticsFactory.register("funnel_from_events_builder", "spark", sp.FunnelFromEventsBuilderSpark)
    BusinessStatisticsFactory.register("conversion_funnel_calculator", "pandas", p.ConversionFunnelCalculatorPandas)
    BusinessStatisticsFactory.register("conversion_funnel_calculator", "polars", pl.ConversionFunnelCalculatorPolars)
    BusinessStatisticsFactory.register("conversion_funnel_calculator", "spark", sp.ConversionFunnelCalculatorSpark)
    BusinessStatisticsFactory.register("simple_clv_calculator", "pandas", p.SimpleCLVCalculatorPandas)
    BusinessStatisticsFactory.register("simple_clv_calculator", "polars", pl.SimpleCLVCalculatorPolars)
    BusinessStatisticsFactory.register("simple_clv_calculator", "spark", sp.SimpleCLVCalculatorSpark)
    BusinessStatisticsFactory.register("discounted_clv_calculator", "pandas", p.DiscountedCLVCalculatorPandas)
    BusinessStatisticsFactory.register("discounted_clv_calculator", "polars", pl.DiscountedCLVCalculatorPolars)
    BusinessStatisticsFactory.register("discounted_clv_calculator", "spark", sp.DiscountedCLVCalculatorSpark)
    BusinessStatisticsFactory.register("clv_segment_assigner", "pandas", p.CLVSegmentAssignerPandas)
    BusinessStatisticsFactory.register("clv_segment_assigner", "polars", pl.CLVSegmentAssignerPolars)
    BusinessStatisticsFactory.register("clv_segment_assigner", "spark", sp.CLVSegmentAssignerSpark)
    BusinessStatisticsFactory.register("customer_lifetime_value_calculator", "pandas", p.CustomerLifetimeValueCalculatorPandas)
    BusinessStatisticsFactory.register("customer_lifetime_value_calculator", "polars", pl.CustomerLifetimeValueCalculatorPolars)
    BusinessStatisticsFactory.register("customer_lifetime_value_calculator", "spark", sp.CustomerLifetimeValueCalculatorSpark)
    BusinessStatisticsFactory.register("base_ratio_calculator", "pandas", p.BaseRatioCalculatorPandas)
    BusinessStatisticsFactory.register("base_ratio_calculator", "polars", pl.BaseRatioCalculatorPolars)
    BusinessStatisticsFactory.register("base_ratio_calculator", "spark", sp.BaseRatioCalculatorSpark)
    BusinessStatisticsFactory.register("gross_margin_calculator", "pandas", p.GrossMarginCalculatorPandas)
    BusinessStatisticsFactory.register("gross_margin_calculator", "polars", pl.GrossMarginCalculatorPolars)
    BusinessStatisticsFactory.register("gross_margin_calculator", "spark", sp.GrossMarginCalculatorSpark)
    BusinessStatisticsFactory.register("net_margin_calculator", "pandas", p.NetMarginCalculatorPandas)
    BusinessStatisticsFactory.register("net_margin_calculator", "polars", pl.NetMarginCalculatorPolars)
    BusinessStatisticsFactory.register("net_margin_calculator", "spark", sp.NetMarginCalculatorSpark)
    BusinessStatisticsFactory.register("roe_calculator", "pandas", p.ROECalculatorPandas)
    BusinessStatisticsFactory.register("roe_calculator", "polars", pl.ROECalculatorPolars)
    BusinessStatisticsFactory.register("roe_calculator", "spark", sp.ROECalculatorSpark)
    BusinessStatisticsFactory.register("roa_calculator", "pandas", p.ROACalculatorPandas)
    BusinessStatisticsFactory.register("roa_calculator", "polars", pl.ROACalculatorPolars)
    BusinessStatisticsFactory.register("roa_calculator", "spark", sp.ROACalculatorSpark)
    BusinessStatisticsFactory.register("current_ratio_calculator", "pandas", p.CurrentRatioCalculatorPandas)
    BusinessStatisticsFactory.register("current_ratio_calculator", "polars", pl.CurrentRatioCalculatorPolars)
    BusinessStatisticsFactory.register("current_ratio_calculator", "spark", sp.CurrentRatioCalculatorSpark)
    BusinessStatisticsFactory.register("quick_ratio_calculator", "pandas", p.QuickRatioCalculatorPandas)
    BusinessStatisticsFactory.register("quick_ratio_calculator", "polars", pl.QuickRatioCalculatorPolars)
    BusinessStatisticsFactory.register("quick_ratio_calculator", "spark", sp.QuickRatioCalculatorSpark)
    BusinessStatisticsFactory.register("debt_to_equity_calculator", "pandas", p.DebtToEquityCalculatorPandas)
    BusinessStatisticsFactory.register("debt_to_equity_calculator", "polars", pl.DebtToEquityCalculatorPolars)
    BusinessStatisticsFactory.register("debt_to_equity_calculator", "spark", sp.DebtToEquityCalculatorSpark)
    BusinessStatisticsFactory.register("asset_turnover_calculator", "pandas", p.AssetTurnoverCalculatorPandas)
    BusinessStatisticsFactory.register("asset_turnover_calculator", "polars", pl.AssetTurnoverCalculatorPolars)
    BusinessStatisticsFactory.register("asset_turnover_calculator", "spark", sp.AssetTurnoverCalculatorSpark)
    BusinessStatisticsFactory.register("inventory_turnover_calculator", "pandas", p.InventoryTurnoverCalculatorPandas)
    BusinessStatisticsFactory.register("inventory_turnover_calculator", "polars", pl.InventoryTurnoverCalculatorPolars)
    BusinessStatisticsFactory.register("inventory_turnover_calculator", "spark", sp.InventoryTurnoverCalculatorSpark)
    BusinessStatisticsFactory.register("financial_ratios_calculator", "pandas", p.FinancialRatiosCalculatorPandas)
    BusinessStatisticsFactory.register("financial_ratios_calculator", "polars", pl.FinancialRatiosCalculatorPolars)
    BusinessStatisticsFactory.register("financial_ratios_calculator", "spark", sp.FinancialRatiosCalculatorSpark)
    BusinessStatisticsFactory.register("period_over_period_calculator", "pandas", p.PeriodOverPeriodCalculatorPandas)
    BusinessStatisticsFactory.register("period_over_period_calculator", "polars", pl.PeriodOverPeriodCalculatorPolars)
    BusinessStatisticsFactory.register("period_over_period_calculator", "spark", sp.PeriodOverPeriodCalculatorSpark)
    BusinessStatisticsFactory.register("cagr_calculator", "pandas", p.CAGRCalculatorPandas)
    BusinessStatisticsFactory.register("cagr_calculator", "polars", pl.CAGRCalculatorPolars)
    BusinessStatisticsFactory.register("cagr_calculator", "spark", sp.CAGRCalculatorSpark)
    BusinessStatisticsFactory.register("rolling_growth_calculator", "pandas", p.RollingGrowthCalculatorPandas)
    BusinessStatisticsFactory.register("rolling_growth_calculator", "polars", pl.RollingGrowthCalculatorPolars)
    BusinessStatisticsFactory.register("rolling_growth_calculator", "spark", sp.RollingGrowthCalculatorSpark)
    BusinessStatisticsFactory.register("growth_rates_calculator", "pandas", p.GrowthRatesCalculatorPandas)
    BusinessStatisticsFactory.register("growth_rates_calculator", "polars", pl.GrowthRatesCalculatorPolars)
    BusinessStatisticsFactory.register("growth_rates_calculator", "spark", sp.GrowthRatesCalculatorSpark)
    BusinessStatisticsFactory.register("pareto_threshold_finder", "pandas", p.ParetoThresholdFinderPandas)
    BusinessStatisticsFactory.register("pareto_threshold_finder", "polars", pl.ParetoThresholdFinderPolars)
    BusinessStatisticsFactory.register("pareto_threshold_finder", "spark", sp.ParetoThresholdFinderSpark)
    BusinessStatisticsFactory.register("pareto_concentration_calculator", "pandas", p.ParetoConcentrationCalculatorPandas)
    BusinessStatisticsFactory.register("pareto_concentration_calculator", "polars", pl.ParetoConcentrationCalculatorPolars)
    BusinessStatisticsFactory.register("pareto_concentration_calculator", "spark", sp.ParetoConcentrationCalculatorSpark)
    BusinessStatisticsFactory.register("pareto_analysis_calculator", "pandas", p.ParetoAnalysisCalculatorPandas)
    BusinessStatisticsFactory.register("pareto_analysis_calculator", "polars", pl.ParetoAnalysisCalculatorPolars)
    BusinessStatisticsFactory.register("pareto_analysis_calculator", "spark", sp.ParetoAnalysisCalculatorSpark)
    BusinessStatisticsFactory.register("returns_computer", "pandas", p.ReturnsComputerPandas)
    BusinessStatisticsFactory.register("returns_computer", "polars", pl.ReturnsComputerPolars)
    BusinessStatisticsFactory.register("returns_computer", "spark", sp.ReturnsComputerSpark)
    BusinessStatisticsFactory.register("va_r_calculator", "pandas", p.VaRCalculatorPandas)
    BusinessStatisticsFactory.register("va_r_calculator", "polars", pl.VaRCalculatorPolars)
    BusinessStatisticsFactory.register("va_r_calculator", "spark", sp.VaRCalculatorSpark)
    BusinessStatisticsFactory.register("c_va_r_calculator", "pandas", p.CVaRCalculatorPandas)
    BusinessStatisticsFactory.register("c_va_r_calculator", "polars", pl.CVaRCalculatorPolars)
    BusinessStatisticsFactory.register("c_va_r_calculator", "spark", sp.CVaRCalculatorSpark)
    BusinessStatisticsFactory.register("sharpe_ratio_calculator", "pandas", p.SharpeRatioCalculatorPandas)
    BusinessStatisticsFactory.register("sharpe_ratio_calculator", "polars", pl.SharpeRatioCalculatorPolars)
    BusinessStatisticsFactory.register("sharpe_ratio_calculator", "spark", sp.SharpeRatioCalculatorSpark)
    BusinessStatisticsFactory.register("sortino_ratio_calculator", "pandas", p.SortinoRatioCalculatorPandas)
    BusinessStatisticsFactory.register("sortino_ratio_calculator", "polars", pl.SortinoRatioCalculatorPolars)
    BusinessStatisticsFactory.register("sortino_ratio_calculator", "spark", sp.SortinoRatioCalculatorSpark)
    BusinessStatisticsFactory.register("max_drawdown_calculator", "pandas", p.MaxDrawdownCalculatorPandas)
    BusinessStatisticsFactory.register("max_drawdown_calculator", "polars", pl.MaxDrawdownCalculatorPolars)
    BusinessStatisticsFactory.register("max_drawdown_calculator", "spark", sp.MaxDrawdownCalculatorSpark)
    BusinessStatisticsFactory.register("calmar_ratio_calculator", "pandas", p.CalmarRatioCalculatorPandas)
    BusinessStatisticsFactory.register("calmar_ratio_calculator", "polars", pl.CalmarRatioCalculatorPolars)
    BusinessStatisticsFactory.register("calmar_ratio_calculator", "spark", sp.CalmarRatioCalculatorSpark)
    BusinessStatisticsFactory.register("risk_metrics_calculator", "pandas", p.RiskMetricsCalculatorPandas)
    BusinessStatisticsFactory.register("risk_metrics_calculator", "polars", pl.RiskMetricsCalculatorPolars)
    BusinessStatisticsFactory.register("risk_metrics_calculator", "spark", sp.RiskMetricsCalculatorSpark)
    BusinessStatisticsFactory.register("simple_run_rate_projector", "pandas", p.SimpleRunRateProjectorPandas)
    BusinessStatisticsFactory.register("simple_run_rate_projector", "polars", pl.SimpleRunRateProjectorPolars)
    BusinessStatisticsFactory.register("simple_run_rate_projector", "spark", sp.SimpleRunRateProjectorSpark)
    BusinessStatisticsFactory.register("trailing_average_projector", "pandas", p.TrailingAverageProjectorPandas)
    BusinessStatisticsFactory.register("trailing_average_projector", "polars", pl.TrailingAverageProjectorPolars)
    BusinessStatisticsFactory.register("trailing_average_projector", "spark", sp.TrailingAverageProjectorSpark)
    BusinessStatisticsFactory.register("weighted_recent_projector", "pandas", p.WeightedRecentProjectorPandas)
    BusinessStatisticsFactory.register("weighted_recent_projector", "polars", pl.WeightedRecentProjectorPolars)
    BusinessStatisticsFactory.register("weighted_recent_projector", "spark", sp.WeightedRecentProjectorSpark)
    BusinessStatisticsFactory.register("run_rate_calculator", "pandas", p.RunRateCalculatorPandas)
    BusinessStatisticsFactory.register("run_rate_calculator", "polars", pl.RunRateCalculatorPolars)
    BusinessStatisticsFactory.register("run_rate_calculator", "spark", sp.RunRateCalculatorSpark)

_register()
