"""Factory — domain `ml_support`."""
from __future__ import annotations
from typing import Any
from core.abstract_factory import RegistryFactory

class MlSupportStatisticsFactory(RegistryFactory[str, Any]):
    pass

def _register() -> None:
    from statistics.ml_support.backends import pandas_impl as p
    from statistics.ml_support.backends import polars_impl as pl
    from statistics.ml_support.backends import spark_impl as sp

    MlSupportStatisticsFactory.register("gini_impurity_calculator", "pandas", p.GiniImpurityCalculatorPandas)
    MlSupportStatisticsFactory.register("gini_impurity_calculator", "polars", pl.GiniImpurityCalculatorPolars)
    MlSupportStatisticsFactory.register("gini_impurity_calculator", "spark", sp.GiniImpurityCalculatorSpark)
    MlSupportStatisticsFactory.register("imbalance_ratio_calculator", "pandas", p.ImbalanceRatioCalculatorPandas)
    MlSupportStatisticsFactory.register("imbalance_ratio_calculator", "polars", pl.ImbalanceRatioCalculatorPolars)
    MlSupportStatisticsFactory.register("imbalance_ratio_calculator", "spark", sp.ImbalanceRatioCalculatorSpark)
    MlSupportStatisticsFactory.register("strategy_advisor", "pandas", p.StrategyAdvisorPandas)
    MlSupportStatisticsFactory.register("strategy_advisor", "polars", pl.StrategyAdvisorPolars)
    MlSupportStatisticsFactory.register("strategy_advisor", "spark", sp.StrategyAdvisorSpark)
    MlSupportStatisticsFactory.register("class_imbalance_calculator", "pandas", p.ClassImbalanceCalculatorPandas)
    MlSupportStatisticsFactory.register("class_imbalance_calculator", "polars", pl.ClassImbalanceCalculatorPolars)
    MlSupportStatisticsFactory.register("class_imbalance_calculator", "spark", sp.ClassImbalanceCalculatorSpark)
    MlSupportStatisticsFactory.register("cv_strategy_selector", "pandas", p.CVStrategySelectorPandas)
    MlSupportStatisticsFactory.register("cv_strategy_selector", "polars", pl.CVStrategySelectorPolars)
    MlSupportStatisticsFactory.register("cv_strategy_selector", "spark", sp.CVStrategySelectorSpark)
    MlSupportStatisticsFactory.register("cv_confidence_interval_calculator", "pandas", p.CVConfidenceIntervalCalculatorPandas)
    MlSupportStatisticsFactory.register("cv_confidence_interval_calculator", "polars", pl.CVConfidenceIntervalCalculatorPolars)
    MlSupportStatisticsFactory.register("cv_confidence_interval_calculator", "spark", sp.CVConfidenceIntervalCalculatorSpark)
    MlSupportStatisticsFactory.register("cross_validation_calculator", "pandas", p.CrossValidationCalculatorPandas)
    MlSupportStatisticsFactory.register("cross_validation_calculator", "polars", pl.CrossValidationCalculatorPolars)
    MlSupportStatisticsFactory.register("cross_validation_calculator", "spark", sp.CrossValidationCalculatorSpark)
    MlSupportStatisticsFactory.register("covariance_matrix_computer", "pandas", p.CovarianceMatrixComputerPandas)
    MlSupportStatisticsFactory.register("covariance_matrix_computer", "polars", pl.CovarianceMatrixComputerPolars)
    MlSupportStatisticsFactory.register("covariance_matrix_computer", "spark", sp.CovarianceMatrixComputerSpark)
    MlSupportStatisticsFactory.register("eigen_decomposition_calculator", "pandas", p.EigenDecompositionCalculatorPandas)
    MlSupportStatisticsFactory.register("eigen_decomposition_calculator", "polars", pl.EigenDecompositionCalculatorPolars)
    MlSupportStatisticsFactory.register("eigen_decomposition_calculator", "spark", sp.EigenDecompositionCalculatorSpark)
    MlSupportStatisticsFactory.register("optimal_component_selector", "pandas", p.OptimalComponentSelectorPandas)
    MlSupportStatisticsFactory.register("optimal_component_selector", "polars", pl.OptimalComponentSelectorPolars)
    MlSupportStatisticsFactory.register("optimal_component_selector", "spark", sp.OptimalComponentSelectorSpark)
    MlSupportStatisticsFactory.register("dimensionality_reduction_calculator", "pandas", p.DimensionalityReductionCalculatorPandas)
    MlSupportStatisticsFactory.register("dimensionality_reduction_calculator", "polars", pl.DimensionalityReductionCalculatorPolars)
    MlSupportStatisticsFactory.register("dimensionality_reduction_calculator", "spark", sp.DimensionalityReductionCalculatorSpark)
    MlSupportStatisticsFactory.register("base_importance_extractor", "pandas", p.BaseImportanceExtractorPandas)
    MlSupportStatisticsFactory.register("base_importance_extractor", "polars", pl.BaseImportanceExtractorPolars)
    MlSupportStatisticsFactory.register("base_importance_extractor", "spark", sp.BaseImportanceExtractorSpark)
    MlSupportStatisticsFactory.register("gini_importance_extractor", "pandas", p.GiniImportanceExtractorPandas)
    MlSupportStatisticsFactory.register("gini_importance_extractor", "polars", pl.GiniImportanceExtractorPolars)
    MlSupportStatisticsFactory.register("gini_importance_extractor", "spark", sp.GiniImportanceExtractorSpark)
    MlSupportStatisticsFactory.register("permutation_importance_extractor", "pandas", p.PermutationImportanceExtractorPandas)
    MlSupportStatisticsFactory.register("permutation_importance_extractor", "polars", pl.PermutationImportanceExtractorPolars)
    MlSupportStatisticsFactory.register("permutation_importance_extractor", "spark", sp.PermutationImportanceExtractorSpark)
    MlSupportStatisticsFactory.register("importance_ranker", "pandas", p.ImportanceRankerPandas)
    MlSupportStatisticsFactory.register("importance_ranker", "polars", pl.ImportanceRankerPolars)
    MlSupportStatisticsFactory.register("importance_ranker", "spark", sp.ImportanceRankerSpark)
    MlSupportStatisticsFactory.register("feature_importance_calculator", "pandas", p.FeatureImportanceCalculatorPandas)
    MlSupportStatisticsFactory.register("feature_importance_calculator", "polars", pl.FeatureImportanceCalculatorPolars)
    MlSupportStatisticsFactory.register("feature_importance_calculator", "spark", sp.FeatureImportanceCalculatorSpark)
    MlSupportStatisticsFactory.register("base_feature_scoring_method", "pandas", p.BaseFeatureScoringMethodPandas)
    MlSupportStatisticsFactory.register("base_feature_scoring_method", "polars", pl.BaseFeatureScoringMethodPolars)
    MlSupportStatisticsFactory.register("base_feature_scoring_method", "spark", sp.BaseFeatureScoringMethodSpark)
    MlSupportStatisticsFactory.register("chi2_scorer", "pandas", p.Chi2ScorerPandas)
    MlSupportStatisticsFactory.register("chi2_scorer", "polars", pl.Chi2ScorerPolars)
    MlSupportStatisticsFactory.register("chi2_scorer", "spark", sp.Chi2ScorerSpark)
    MlSupportStatisticsFactory.register("anovaf_scorer", "pandas", p.ANOVAFScorerPandas)
    MlSupportStatisticsFactory.register("anovaf_scorer", "polars", pl.ANOVAFScorerPolars)
    MlSupportStatisticsFactory.register("anovaf_scorer", "spark", sp.ANOVAFScorerSpark)
    MlSupportStatisticsFactory.register("mi_scorer", "pandas", p.MIScorerPandas)
    MlSupportStatisticsFactory.register("mi_scorer", "polars", pl.MIScorerPolars)
    MlSupportStatisticsFactory.register("mi_scorer", "spark", sp.MIScorerSpark)
    MlSupportStatisticsFactory.register("score_ranker", "pandas", p.ScoreRankerPandas)
    MlSupportStatisticsFactory.register("score_ranker", "polars", pl.ScoreRankerPolars)
    MlSupportStatisticsFactory.register("score_ranker", "spark", sp.ScoreRankerSpark)
    MlSupportStatisticsFactory.register("feature_selection_calculator", "pandas", p.FeatureSelectionCalculatorPandas)
    MlSupportStatisticsFactory.register("feature_selection_calculator", "polars", pl.FeatureSelectionCalculatorPolars)
    MlSupportStatisticsFactory.register("feature_selection_calculator", "spark", sp.FeatureSelectionCalculatorSpark)
    MlSupportStatisticsFactory.register("variance_computer", "pandas", p.VarianceComputerPandas)
    MlSupportStatisticsFactory.register("variance_computer", "polars", pl.VarianceComputerPolars)
    MlSupportStatisticsFactory.register("variance_computer", "spark", sp.VarianceComputerSpark)
    MlSupportStatisticsFactory.register("frequency_ratio_computer", "pandas", p.FrequencyRatioComputerPandas)
    MlSupportStatisticsFactory.register("frequency_ratio_computer", "polars", pl.FrequencyRatioComputerPolars)
    MlSupportStatisticsFactory.register("frequency_ratio_computer", "spark", sp.FrequencyRatioComputerSpark)
    MlSupportStatisticsFactory.register("near_zero_variance_classifier", "pandas", p.NearZeroVarianceClassifierPandas)
    MlSupportStatisticsFactory.register("near_zero_variance_classifier", "polars", pl.NearZeroVarianceClassifierPolars)
    MlSupportStatisticsFactory.register("near_zero_variance_classifier", "spark", sp.NearZeroVarianceClassifierSpark)
    MlSupportStatisticsFactory.register("feature_variance_calculator", "pandas", p.FeatureVarianceCalculatorPandas)
    MlSupportStatisticsFactory.register("feature_variance_calculator", "polars", pl.FeatureVarianceCalculatorPolars)
    MlSupportStatisticsFactory.register("feature_variance_calculator", "spark", sp.FeatureVarianceCalculatorSpark)
    MlSupportStatisticsFactory.register("bias_variance_diagnostic", "pandas", p.BiasVarianceDiagnosticPandas)
    MlSupportStatisticsFactory.register("bias_variance_diagnostic", "polars", pl.BiasVarianceDiagnosticPolars)
    MlSupportStatisticsFactory.register("bias_variance_diagnostic", "spark", sp.BiasVarianceDiagnosticSpark)
    MlSupportStatisticsFactory.register("training_size_generator", "pandas", p.TrainingSizeGeneratorPandas)
    MlSupportStatisticsFactory.register("training_size_generator", "polars", pl.TrainingSizeGeneratorPolars)
    MlSupportStatisticsFactory.register("training_size_generator", "spark", sp.TrainingSizeGeneratorSpark)
    MlSupportStatisticsFactory.register("learning_curve_calculator", "pandas", p.LearningCurveCalculatorPandas)
    MlSupportStatisticsFactory.register("learning_curve_calculator", "polars", pl.LearningCurveCalculatorPolars)
    MlSupportStatisticsFactory.register("learning_curve_calculator", "spark", sp.LearningCurveCalculatorSpark)
    MlSupportStatisticsFactory.register("residual_normality_checker", "pandas", p.ResidualNormalityCheckerPandas)
    MlSupportStatisticsFactory.register("residual_normality_checker", "polars", pl.ResidualNormalityCheckerPolars)
    MlSupportStatisticsFactory.register("residual_normality_checker", "spark", sp.ResidualNormalityCheckerSpark)
    MlSupportStatisticsFactory.register("homoscedasticity_checker", "pandas", p.HomoscedasticityCheckerPandas)
    MlSupportStatisticsFactory.register("homoscedasticity_checker", "polars", pl.HomoscedasticityCheckerPolars)
    MlSupportStatisticsFactory.register("homoscedasticity_checker", "spark", sp.HomoscedasticityCheckerSpark)
    MlSupportStatisticsFactory.register("autocorrelation_checker", "pandas", p.AutocorrelationCheckerPandas)
    MlSupportStatisticsFactory.register("autocorrelation_checker", "polars", pl.AutocorrelationCheckerPolars)
    MlSupportStatisticsFactory.register("autocorrelation_checker", "spark", sp.AutocorrelationCheckerSpark)
    MlSupportStatisticsFactory.register("model_residuals_calculator", "pandas", p.ModelResidualsCalculatorPandas)
    MlSupportStatisticsFactory.register("model_residuals_calculator", "polars", pl.ModelResidualsCalculatorPolars)
    MlSupportStatisticsFactory.register("model_residuals_calculator", "spark", sp.ModelResidualsCalculatorSpark)

_register()
