"""Factory — domain `descriptive`."""
from __future__ import annotations
from typing import Any
from core.abstract_factory import RegistryFactory

class DescriptiveStatisticsFactory(RegistryFactory[str, Any]):
    pass

def _register() -> None:
    from statistics.descriptive.backends import pandas_impl as p
    from statistics.descriptive.backends import polars_impl as pl
    from statistics.descriptive.backends import spark_impl as sp

    DescriptiveStatisticsFactory.register("mean_calculator", "pandas", p.MeanCalculatorPandas)
    DescriptiveStatisticsFactory.register("mean_calculator", "polars", pl.MeanCalculatorPolars)
    DescriptiveStatisticsFactory.register("mean_calculator", "spark", sp.MeanCalculatorSpark)
    DescriptiveStatisticsFactory.register("median_calculator", "pandas", p.MedianCalculatorPandas)
    DescriptiveStatisticsFactory.register("median_calculator", "polars", pl.MedianCalculatorPolars)
    DescriptiveStatisticsFactory.register("median_calculator", "spark", sp.MedianCalculatorSpark)
    DescriptiveStatisticsFactory.register("mode_calculator", "pandas", p.ModeCalculatorPandas)
    DescriptiveStatisticsFactory.register("mode_calculator", "polars", pl.ModeCalculatorPolars)
    DescriptiveStatisticsFactory.register("mode_calculator", "spark", sp.ModeCalculatorSpark)
    DescriptiveStatisticsFactory.register("trimmed_mean_calculator", "pandas", p.TrimmedMeanCalculatorPandas)
    DescriptiveStatisticsFactory.register("trimmed_mean_calculator", "polars", pl.TrimmedMeanCalculatorPolars)
    DescriptiveStatisticsFactory.register("trimmed_mean_calculator", "spark", sp.TrimmedMeanCalculatorSpark)
    DescriptiveStatisticsFactory.register("central_tendency_interpreter", "pandas", p.CentralTendencyInterpreterPandas)
    DescriptiveStatisticsFactory.register("central_tendency_interpreter", "polars", pl.CentralTendencyInterpreterPolars)
    DescriptiveStatisticsFactory.register("central_tendency_interpreter", "spark", sp.CentralTendencyInterpreterSpark)
    DescriptiveStatisticsFactory.register("central_tendency_calculator", "pandas", p.CentralTendencyCalculatorPandas)
    DescriptiveStatisticsFactory.register("central_tendency_calculator", "polars", pl.CentralTendencyCalculatorPolars)
    DescriptiveStatisticsFactory.register("central_tendency_calculator", "spark", sp.CentralTendencyCalculatorSpark)
    DescriptiveStatisticsFactory.register("variance_calculator", "pandas", p.VarianceCalculatorPandas)
    DescriptiveStatisticsFactory.register("variance_calculator", "polars", pl.VarianceCalculatorPolars)
    DescriptiveStatisticsFactory.register("variance_calculator", "spark", sp.VarianceCalculatorSpark)
    DescriptiveStatisticsFactory.register("standard_deviation_calculator", "pandas", p.StandardDeviationCalculatorPandas)
    DescriptiveStatisticsFactory.register("standard_deviation_calculator", "polars", pl.StandardDeviationCalculatorPolars)
    DescriptiveStatisticsFactory.register("standard_deviation_calculator", "spark", sp.StandardDeviationCalculatorSpark)
    DescriptiveStatisticsFactory.register("range_calculator", "pandas", p.RangeCalculatorPandas)
    DescriptiveStatisticsFactory.register("range_calculator", "polars", pl.RangeCalculatorPolars)
    DescriptiveStatisticsFactory.register("range_calculator", "spark", sp.RangeCalculatorSpark)
    DescriptiveStatisticsFactory.register("iqr_calculator", "pandas", p.IQRCalculatorPandas)
    DescriptiveStatisticsFactory.register("iqr_calculator", "polars", pl.IQRCalculatorPolars)
    DescriptiveStatisticsFactory.register("iqr_calculator", "spark", sp.IQRCalculatorSpark)
    DescriptiveStatisticsFactory.register("mad_calculator", "pandas", p.MADCalculatorPandas)
    DescriptiveStatisticsFactory.register("mad_calculator", "polars", pl.MADCalculatorPolars)
    DescriptiveStatisticsFactory.register("mad_calculator", "spark", sp.MADCalculatorSpark)
    DescriptiveStatisticsFactory.register("coefficient_of_variation_calculator", "pandas", p.CoefficientOfVariationCalculatorPandas)
    DescriptiveStatisticsFactory.register("coefficient_of_variation_calculator", "polars", pl.CoefficientOfVariationCalculatorPolars)
    DescriptiveStatisticsFactory.register("coefficient_of_variation_calculator", "spark", sp.CoefficientOfVariationCalculatorSpark)
    DescriptiveStatisticsFactory.register("dispersion_calculator", "pandas", p.DispersionCalculatorPandas)
    DescriptiveStatisticsFactory.register("dispersion_calculator", "polars", pl.DispersionCalculatorPolars)
    DescriptiveStatisticsFactory.register("dispersion_calculator", "spark", sp.DispersionCalculatorSpark)
    DescriptiveStatisticsFactory.register("bimodality_detector", "pandas", p.BimodalityDetectorPandas)
    DescriptiveStatisticsFactory.register("bimodality_detector", "polars", pl.BimodalityDetectorPolars)
    DescriptiveStatisticsFactory.register("bimodality_detector", "spark", sp.BimodalityDetectorSpark)
    DescriptiveStatisticsFactory.register("transformation_advisor", "pandas", p.TransformationAdvisorPandas)
    DescriptiveStatisticsFactory.register("transformation_advisor", "polars", pl.TransformationAdvisorPolars)
    DescriptiveStatisticsFactory.register("transformation_advisor", "spark", sp.TransformationAdvisorSpark)
    DescriptiveStatisticsFactory.register("distribution_fitter", "pandas", p.DistributionFitterPandas)
    DescriptiveStatisticsFactory.register("distribution_fitter", "polars", pl.DistributionFitterPolars)
    DescriptiveStatisticsFactory.register("distribution_fitter", "spark", sp.DistributionFitterSpark)
    DescriptiveStatisticsFactory.register("distribution_classifier", "pandas", p.DistributionClassifierPandas)
    DescriptiveStatisticsFactory.register("distribution_classifier", "polars", pl.DistributionClassifierPolars)
    DescriptiveStatisticsFactory.register("distribution_classifier", "spark", sp.DistributionClassifierSpark)
    DescriptiveStatisticsFactory.register("bin_count_selector", "pandas", p.BinCountSelectorPandas)
    DescriptiveStatisticsFactory.register("bin_count_selector", "polars", pl.BinCountSelectorPolars)
    DescriptiveStatisticsFactory.register("bin_count_selector", "spark", sp.BinCountSelectorSpark)
    DescriptiveStatisticsFactory.register("frequency_table_builder", "pandas", p.FrequencyTableBuilderPandas)
    DescriptiveStatisticsFactory.register("frequency_table_builder", "polars", pl.FrequencyTableBuilderPolars)
    DescriptiveStatisticsFactory.register("frequency_table_builder", "spark", sp.FrequencyTableBuilderSpark)
    DescriptiveStatisticsFactory.register("frequency_distribution_builder", "pandas", p.FrequencyDistributionBuilderPandas)
    DescriptiveStatisticsFactory.register("frequency_distribution_builder", "polars", pl.FrequencyDistributionBuilderPolars)
    DescriptiveStatisticsFactory.register("frequency_distribution_builder", "spark", sp.FrequencyDistributionBuilderSpark)
    DescriptiveStatisticsFactory.register("base_normality_test", "pandas", p.BaseNormalityTestPandas)
    DescriptiveStatisticsFactory.register("base_normality_test", "polars", pl.BaseNormalityTestPolars)
    DescriptiveStatisticsFactory.register("base_normality_test", "spark", sp.BaseNormalityTestSpark)
    DescriptiveStatisticsFactory.register("shapiro_wilk_test", "pandas", p.ShapiroWilkTestPandas)
    DescriptiveStatisticsFactory.register("shapiro_wilk_test", "polars", pl.ShapiroWilkTestPolars)
    DescriptiveStatisticsFactory.register("shapiro_wilk_test", "spark", sp.ShapiroWilkTestSpark)
    DescriptiveStatisticsFactory.register("anderson_darling_test", "pandas", p.AndersonDarlingTestPandas)
    DescriptiveStatisticsFactory.register("anderson_darling_test", "polars", pl.AndersonDarlingTestPolars)
    DescriptiveStatisticsFactory.register("anderson_darling_test", "spark", sp.AndersonDarlingTestSpark)
    DescriptiveStatisticsFactory.register("kolmogorov_smirnov_test", "pandas", p.KolmogorovSmirnovTestPandas)
    DescriptiveStatisticsFactory.register("kolmogorov_smirnov_test", "polars", pl.KolmogorovSmirnovTestPolars)
    DescriptiveStatisticsFactory.register("kolmogorov_smirnov_test", "spark", sp.KolmogorovSmirnovTestSpark)
    DescriptiveStatisticsFactory.register("normality_test_suite", "pandas", p.NormalityTestSuitePandas)
    DescriptiveStatisticsFactory.register("normality_test_suite", "polars", pl.NormalityTestSuitePolars)
    DescriptiveStatisticsFactory.register("normality_test_suite", "spark", sp.NormalityTestSuiteSpark)
    DescriptiveStatisticsFactory.register("percentile_outlier_detector", "pandas", p.PercentileOutlierDetectorPandas)
    DescriptiveStatisticsFactory.register("percentile_outlier_detector", "polars", pl.PercentileOutlierDetectorPolars)
    DescriptiveStatisticsFactory.register("percentile_outlier_detector", "spark", sp.PercentileOutlierDetectorSpark)
    DescriptiveStatisticsFactory.register("percentiles_calculator", "pandas", p.PercentilesCalculatorPandas)
    DescriptiveStatisticsFactory.register("percentiles_calculator", "polars", pl.PercentilesCalculatorPolars)
    DescriptiveStatisticsFactory.register("percentiles_calculator", "spark", sp.PercentilesCalculatorSpark)
    DescriptiveStatisticsFactory.register("skewness_interpreter", "pandas", p.SkewnessInterpreterPandas)
    DescriptiveStatisticsFactory.register("skewness_interpreter", "polars", pl.SkewnessInterpreterPolars)
    DescriptiveStatisticsFactory.register("skewness_interpreter", "spark", sp.SkewnessInterpreterSpark)
    DescriptiveStatisticsFactory.register("kurtosis_interpreter", "pandas", p.KurtosisInterpreterPandas)
    DescriptiveStatisticsFactory.register("kurtosis_interpreter", "polars", pl.KurtosisInterpreterPolars)
    DescriptiveStatisticsFactory.register("kurtosis_interpreter", "spark", sp.KurtosisInterpreterSpark)
    DescriptiveStatisticsFactory.register("skewness_kurtosis_calculator", "pandas", p.SkewnessKurtosisCalculatorPandas)
    DescriptiveStatisticsFactory.register("skewness_kurtosis_calculator", "polars", pl.SkewnessKurtosisCalculatorPolars)
    DescriptiveStatisticsFactory.register("skewness_kurtosis_calculator", "spark", sp.SkewnessKurtosisCalculatorSpark)
    DescriptiveStatisticsFactory.register("value_counts_calculator", "pandas", p.ValueCountsCalculatorPandas)
    DescriptiveStatisticsFactory.register("value_counts_calculator", "polars", pl.ValueCountsCalculatorPolars)
    DescriptiveStatisticsFactory.register("value_counts_calculator", "spark", sp.ValueCountsCalculatorSpark)

_register()
