"""Factory — domain `relational`."""
from __future__ import annotations
from typing import Any
from core.abstract_factory import RegistryFactory

class RelationalStatisticsFactory(RegistryFactory[str, Any]):
    pass

def _register() -> None:
    from statistics.relational.backends import pandas_impl as p
    from statistics.relational.backends import polars_impl as pl
    from statistics.relational.backends import spark_impl as sp

    RelationalStatisticsFactory.register("odds_ratio_calculator", "pandas", p.OddsRatioCalculatorPandas)
    RelationalStatisticsFactory.register("odds_ratio_calculator", "polars", pl.OddsRatioCalculatorPolars)
    RelationalStatisticsFactory.register("odds_ratio_calculator", "spark", sp.OddsRatioCalculatorSpark)
    RelationalStatisticsFactory.register("relative_risk_calculator", "pandas", p.RelativeRiskCalculatorPandas)
    RelationalStatisticsFactory.register("relative_risk_calculator", "polars", pl.RelativeRiskCalculatorPolars)
    RelationalStatisticsFactory.register("relative_risk_calculator", "spark", sp.RelativeRiskCalculatorSpark)
    RelationalStatisticsFactory.register("contingency_analysis_calculator", "pandas", p.ContingencyAnalysisCalculatorPandas)
    RelationalStatisticsFactory.register("contingency_analysis_calculator", "polars", pl.ContingencyAnalysisCalculatorPolars)
    RelationalStatisticsFactory.register("contingency_analysis_calculator", "spark", sp.ContingencyAnalysisCalculatorSpark)
    RelationalStatisticsFactory.register("correlation_matrix_computer", "pandas", p.CorrelationMatrixComputerPandas)
    RelationalStatisticsFactory.register("correlation_matrix_computer", "polars", pl.CorrelationMatrixComputerPolars)
    RelationalStatisticsFactory.register("correlation_matrix_computer", "spark", sp.CorrelationMatrixComputerSpark)
    RelationalStatisticsFactory.register("correlation_pair_extractor", "pandas", p.CorrelationPairExtractorPandas)
    RelationalStatisticsFactory.register("correlation_pair_extractor", "polars", pl.CorrelationPairExtractorPolars)
    RelationalStatisticsFactory.register("correlation_pair_extractor", "spark", sp.CorrelationPairExtractorSpark)
    RelationalStatisticsFactory.register("high_correlation_flag_detector", "pandas", p.HighCorrelationFlagDetectorPandas)
    RelationalStatisticsFactory.register("high_correlation_flag_detector", "polars", pl.HighCorrelationFlagDetectorPolars)
    RelationalStatisticsFactory.register("high_correlation_flag_detector", "spark", sp.HighCorrelationFlagDetectorSpark)
    RelationalStatisticsFactory.register("correlation_matrix_calculator", "pandas", p.CorrelationMatrixCalculatorPandas)
    RelationalStatisticsFactory.register("correlation_matrix_calculator", "polars", pl.CorrelationMatrixCalculatorPolars)
    RelationalStatisticsFactory.register("correlation_matrix_calculator", "spark", sp.CorrelationMatrixCalculatorSpark)
    RelationalStatisticsFactory.register("series_standardizer", "pandas", p.SeriesStandardizerPandas)
    RelationalStatisticsFactory.register("series_standardizer", "polars", pl.SeriesStandardizerPolars)
    RelationalStatisticsFactory.register("series_standardizer", "spark", sp.SeriesStandardizerSpark)
    RelationalStatisticsFactory.register("lagged_correlation_computer", "pandas", p.LaggedCorrelationComputerPandas)
    RelationalStatisticsFactory.register("lagged_correlation_computer", "polars", pl.LaggedCorrelationComputerPolars)
    RelationalStatisticsFactory.register("lagged_correlation_computer", "spark", sp.LaggedCorrelationComputerSpark)
    RelationalStatisticsFactory.register("peak_lag_detector", "pandas", p.PeakLagDetectorPandas)
    RelationalStatisticsFactory.register("peak_lag_detector", "polars", pl.PeakLagDetectorPolars)
    RelationalStatisticsFactory.register("peak_lag_detector", "spark", sp.PeakLagDetectorSpark)
    RelationalStatisticsFactory.register("cross_correlation_calculator", "pandas", p.CrossCorrelationCalculatorPandas)
    RelationalStatisticsFactory.register("cross_correlation_calculator", "polars", pl.CrossCorrelationCalculatorPolars)
    RelationalStatisticsFactory.register("cross_correlation_calculator", "spark", sp.CrossCorrelationCalculatorSpark)
    RelationalStatisticsFactory.register("lagged_design_matrix_builder", "pandas", p.LaggedDesignMatrixBuilderPandas)
    RelationalStatisticsFactory.register("lagged_design_matrix_builder", "polars", pl.LaggedDesignMatrixBuilderPolars)
    RelationalStatisticsFactory.register("lagged_design_matrix_builder", "spark", sp.LaggedDesignMatrixBuilderSpark)
    RelationalStatisticsFactory.register("ols_residual_calculator", "pandas", p.OLSResidualCalculatorPandas)
    RelationalStatisticsFactory.register("ols_residual_calculator", "polars", pl.OLSResidualCalculatorPolars)
    RelationalStatisticsFactory.register("ols_residual_calculator", "spark", sp.OLSResidualCalculatorSpark)
    RelationalStatisticsFactory.register("granger_f_statistic_calculator", "pandas", p.GrangerFStatisticCalculatorPandas)
    RelationalStatisticsFactory.register("granger_f_statistic_calculator", "polars", pl.GrangerFStatisticCalculatorPolars)
    RelationalStatisticsFactory.register("granger_f_statistic_calculator", "spark", sp.GrangerFStatisticCalculatorSpark)
    RelationalStatisticsFactory.register("granger_causality_calculator", "pandas", p.GrangerCausalityCalculatorPandas)
    RelationalStatisticsFactory.register("granger_causality_calculator", "polars", pl.GrangerCausalityCalculatorPolars)
    RelationalStatisticsFactory.register("granger_causality_calculator", "spark", sp.GrangerCausalityCalculatorSpark)
    RelationalStatisticsFactory.register("additive_model_evaluator", "pandas", p.AdditiveModelEvaluatorPandas)
    RelationalStatisticsFactory.register("additive_model_evaluator", "polars", pl.AdditiveModelEvaluatorPolars)
    RelationalStatisticsFactory.register("additive_model_evaluator", "spark", sp.AdditiveModelEvaluatorSpark)
    RelationalStatisticsFactory.register("interaction_model_evaluator", "pandas", p.InteractionModelEvaluatorPandas)
    RelationalStatisticsFactory.register("interaction_model_evaluator", "polars", pl.InteractionModelEvaluatorPolars)
    RelationalStatisticsFactory.register("interaction_model_evaluator", "spark", sp.InteractionModelEvaluatorSpark)
    RelationalStatisticsFactory.register("interaction_gain_classifier", "pandas", p.InteractionGainClassifierPandas)
    RelationalStatisticsFactory.register("interaction_gain_classifier", "polars", pl.InteractionGainClassifierPolars)
    RelationalStatisticsFactory.register("interaction_gain_classifier", "spark", sp.InteractionGainClassifierSpark)
    RelationalStatisticsFactory.register("interaction_effects_calculator", "pandas", p.InteractionEffectsCalculatorPandas)
    RelationalStatisticsFactory.register("interaction_effects_calculator", "polars", pl.InteractionEffectsCalculatorPolars)
    RelationalStatisticsFactory.register("interaction_effects_calculator", "spark", sp.InteractionEffectsCalculatorSpark)
    RelationalStatisticsFactory.register("vif_risk_classifier", "pandas", p.VIFRiskClassifierPandas)
    RelationalStatisticsFactory.register("vif_risk_classifier", "polars", pl.VIFRiskClassifierPolars)
    RelationalStatisticsFactory.register("vif_risk_classifier", "spark", sp.VIFRiskClassifierSpark)
    RelationalStatisticsFactory.register("single_feature_vif_calculator", "pandas", p.SingleFeatureVIFCalculatorPandas)
    RelationalStatisticsFactory.register("single_feature_vif_calculator", "polars", pl.SingleFeatureVIFCalculatorPolars)
    RelationalStatisticsFactory.register("single_feature_vif_calculator", "spark", sp.SingleFeatureVIFCalculatorSpark)
    RelationalStatisticsFactory.register("multicollinearity_calculator", "pandas", p.MulticollinearityCalculatorPandas)
    RelationalStatisticsFactory.register("multicollinearity_calculator", "polars", pl.MulticollinearityCalculatorPolars)
    RelationalStatisticsFactory.register("multicollinearity_calculator", "spark", sp.MulticollinearityCalculatorSpark)
    RelationalStatisticsFactory.register("target_type_detector", "pandas", p.TargetTypeDetectorPandas)
    RelationalStatisticsFactory.register("target_type_detector", "polars", pl.TargetTypeDetectorPolars)
    RelationalStatisticsFactory.register("target_type_detector", "spark", sp.TargetTypeDetectorSpark)
    RelationalStatisticsFactory.register("mi_score_normalizer", "pandas", p.MIScoreNormalizerPandas)
    RelationalStatisticsFactory.register("mi_score_normalizer", "polars", pl.MIScoreNormalizerPolars)
    RelationalStatisticsFactory.register("mi_score_normalizer", "spark", sp.MIScoreNormalizerSpark)
    RelationalStatisticsFactory.register("mutual_information_calculator", "pandas", p.MutualInformationCalculatorPandas)
    RelationalStatisticsFactory.register("mutual_information_calculator", "polars", pl.MutualInformationCalculatorPolars)
    RelationalStatisticsFactory.register("mutual_information_calculator", "spark", sp.MutualInformationCalculatorSpark)
    RelationalStatisticsFactory.register("residual_extractor", "pandas", p.ResidualExtractorPandas)
    RelationalStatisticsFactory.register("residual_extractor", "polars", pl.ResidualExtractorPolars)
    RelationalStatisticsFactory.register("residual_extractor", "spark", sp.ResidualExtractorSpark)
    RelationalStatisticsFactory.register("partial_correlation_calculator", "pandas", p.PartialCorrelationCalculatorPandas)
    RelationalStatisticsFactory.register("partial_correlation_calculator", "polars", pl.PartialCorrelationCalculatorPolars)
    RelationalStatisticsFactory.register("partial_correlation_calculator", "spark", sp.PartialCorrelationCalculatorSpark)

_register()
