"""Factory — domain `nlp`."""
from __future__ import annotations
from typing import Any
from core.abstract_factory import RegistryFactory

class NlpStatisticsFactory(RegistryFactory[str, Any]):
    pass

def _register() -> None:
    from statistics.nlp.backends import pandas_impl as p
    from statistics.nlp.backends import polars_impl as pl
    from statistics.nlp.backends import spark_impl as sp

    NlpStatisticsFactory.register("trigram_extractor", "pandas", p.TrigramExtractorPandas)
    NlpStatisticsFactory.register("trigram_extractor", "polars", pl.TrigramExtractorPolars)
    NlpStatisticsFactory.register("trigram_extractor", "spark", sp.TrigramExtractorSpark)
    NlpStatisticsFactory.register("language_profile_library", "pandas", p.LanguageProfileLibraryPandas)
    NlpStatisticsFactory.register("language_profile_library", "polars", pl.LanguageProfileLibraryPolars)
    NlpStatisticsFactory.register("language_profile_library", "spark", sp.LanguageProfileLibrarySpark)
    NlpStatisticsFactory.register("language_scorer", "pandas", p.LanguageScorerPandas)
    NlpStatisticsFactory.register("language_scorer", "polars", pl.LanguageScorerPolars)
    NlpStatisticsFactory.register("language_scorer", "spark", sp.LanguageScorerSpark)
    NlpStatisticsFactory.register("language_detection_calculator", "pandas", p.LanguageDetectionCalculatorPandas)
    NlpStatisticsFactory.register("language_detection_calculator", "polars", pl.LanguageDetectionCalculatorPolars)
    NlpStatisticsFactory.register("language_detection_calculator", "spark", sp.LanguageDetectionCalculatorSpark)
    NlpStatisticsFactory.register("document_entity_extractor", "pandas", p.DocumentEntityExtractorPandas)
    NlpStatisticsFactory.register("document_entity_extractor", "polars", pl.DocumentEntityExtractorPolars)
    NlpStatisticsFactory.register("document_entity_extractor", "spark", sp.DocumentEntityExtractorSpark)
    NlpStatisticsFactory.register("entity_density_computer", "pandas", p.EntityDensityComputerPandas)
    NlpStatisticsFactory.register("entity_density_computer", "polars", pl.EntityDensityComputerPolars)
    NlpStatisticsFactory.register("entity_density_computer", "spark", sp.EntityDensityComputerSpark)
    NlpStatisticsFactory.register("named_entity_density_calculator", "pandas", p.NamedEntityDensityCalculatorPandas)
    NlpStatisticsFactory.register("named_entity_density_calculator", "polars", pl.NamedEntityDensityCalculatorPolars)
    NlpStatisticsFactory.register("named_entity_density_calculator", "spark", sp.NamedEntityDensityCalculatorSpark)
    NlpStatisticsFactory.register("token_sentiment_scorer", "pandas", p.TokenSentimentScorerPandas)
    NlpStatisticsFactory.register("token_sentiment_scorer", "polars", pl.TokenSentimentScorerPolars)
    NlpStatisticsFactory.register("token_sentiment_scorer", "spark", sp.TokenSentimentScorerSpark)
    NlpStatisticsFactory.register("polarity_normalizer", "pandas", p.PolarityNormalizerPandas)
    NlpStatisticsFactory.register("polarity_normalizer", "polars", pl.PolarityNormalizerPolars)
    NlpStatisticsFactory.register("polarity_normalizer", "spark", sp.PolarityNormalizerSpark)
    NlpStatisticsFactory.register("subjectivity_estimator", "pandas", p.SubjectivityEstimatorPandas)
    NlpStatisticsFactory.register("subjectivity_estimator", "polars", pl.SubjectivityEstimatorPolars)
    NlpStatisticsFactory.register("subjectivity_estimator", "spark", sp.SubjectivityEstimatorSpark)
    NlpStatisticsFactory.register("sentiment_label_assigner", "pandas", p.SentimentLabelAssignerPandas)
    NlpStatisticsFactory.register("sentiment_label_assigner", "polars", pl.SentimentLabelAssignerPolars)
    NlpStatisticsFactory.register("sentiment_label_assigner", "spark", sp.SentimentLabelAssignerSpark)
    NlpStatisticsFactory.register("sentiment_analysis_calculator", "pandas", p.SentimentAnalysisCalculatorPandas)
    NlpStatisticsFactory.register("sentiment_analysis_calculator", "polars", pl.SentimentAnalysisCalculatorPolars)
    NlpStatisticsFactory.register("sentiment_analysis_calculator", "spark", sp.SentimentAnalysisCalculatorSpark)
    NlpStatisticsFactory.register("text_normalizer", "pandas", p.TextNormalizerPandas)
    NlpStatisticsFactory.register("text_normalizer", "polars", pl.TextNormalizerPolars)
    NlpStatisticsFactory.register("text_normalizer", "spark", sp.TextNormalizerSpark)
    NlpStatisticsFactory.register("word_tokenizer", "pandas", p.WordTokenizerPandas)
    NlpStatisticsFactory.register("word_tokenizer", "polars", pl.WordTokenizerPolars)
    NlpStatisticsFactory.register("word_tokenizer", "spark", sp.WordTokenizerSpark)
    NlpStatisticsFactory.register("sentence_tokenizer", "pandas", p.SentenceTokenizerPandas)
    NlpStatisticsFactory.register("sentence_tokenizer", "polars", pl.SentenceTokenizerPolars)
    NlpStatisticsFactory.register("sentence_tokenizer", "spark", sp.SentenceTokenizerSpark)
    NlpStatisticsFactory.register("lexical_density_calculator", "pandas", p.LexicalDensityCalculatorPandas)
    NlpStatisticsFactory.register("lexical_density_calculator", "polars", pl.LexicalDensityCalculatorPolars)
    NlpStatisticsFactory.register("lexical_density_calculator", "spark", sp.LexicalDensityCalculatorSpark)
    NlpStatisticsFactory.register("document_stats_computer", "pandas", p.DocumentStatsComputerPandas)
    NlpStatisticsFactory.register("document_stats_computer", "polars", pl.DocumentStatsComputerPolars)
    NlpStatisticsFactory.register("document_stats_computer", "spark", sp.DocumentStatsComputerSpark)
    NlpStatisticsFactory.register("text_basic_stats_calculator", "pandas", p.TextBasicStatsCalculatorPandas)
    NlpStatisticsFactory.register("text_basic_stats_calculator", "polars", pl.TextBasicStatsCalculatorPolars)
    NlpStatisticsFactory.register("text_basic_stats_calculator", "spark", sp.TextBasicStatsCalculatorSpark)
    NlpStatisticsFactory.register("tfidf_vectorizer", "pandas", p.TFIDFVectorizerPandas)
    NlpStatisticsFactory.register("tfidf_vectorizer", "polars", pl.TFIDFVectorizerPolars)
    NlpStatisticsFactory.register("tfidf_vectorizer", "spark", sp.TFIDFVectorizerSpark)
    NlpStatisticsFactory.register("cosine_similarity_computer", "pandas", p.CosineSimilarityComputerPandas)
    NlpStatisticsFactory.register("cosine_similarity_computer", "polars", pl.CosineSimilarityComputerPolars)
    NlpStatisticsFactory.register("cosine_similarity_computer", "spark", sp.CosineSimilarityComputerSpark)
    NlpStatisticsFactory.register("similarity_label_assigner", "pandas", p.SimilarityLabelAssignerPandas)
    NlpStatisticsFactory.register("similarity_label_assigner", "polars", pl.SimilarityLabelAssignerPolars)
    NlpStatisticsFactory.register("similarity_label_assigner", "spark", sp.SimilarityLabelAssignerSpark)
    NlpStatisticsFactory.register("text_similarity_calculator", "pandas", p.TextSimilarityCalculatorPandas)
    NlpStatisticsFactory.register("text_similarity_calculator", "polars", pl.TextSimilarityCalculatorPolars)
    NlpStatisticsFactory.register("text_similarity_calculator", "spark", sp.TextSimilarityCalculatorSpark)
    NlpStatisticsFactory.register("bag_of_words_builder", "pandas", p.BagOfWordsBuilderPandas)
    NlpStatisticsFactory.register("bag_of_words_builder", "polars", pl.BagOfWordsBuilderPolars)
    NlpStatisticsFactory.register("bag_of_words_builder", "spark", sp.BagOfWordsBuilderSpark)
    NlpStatisticsFactory.register("nmf_topic_extractor", "pandas", p.NMFTopicExtractorPandas)
    NlpStatisticsFactory.register("nmf_topic_extractor", "polars", pl.NMFTopicExtractorPolars)
    NlpStatisticsFactory.register("nmf_topic_extractor", "spark", sp.NMFTopicExtractorSpark)
    NlpStatisticsFactory.register("tfidf_weighted_matrix_builder", "pandas", p.TFIDFWeightedMatrixBuilderPandas)
    NlpStatisticsFactory.register("tfidf_weighted_matrix_builder", "polars", pl.TFIDFWeightedMatrixBuilderPolars)
    NlpStatisticsFactory.register("tfidf_weighted_matrix_builder", "spark", sp.TFIDFWeightedMatrixBuilderSpark)
    NlpStatisticsFactory.register("topic_detection_calculator", "pandas", p.TopicDetectionCalculatorPandas)
    NlpStatisticsFactory.register("topic_detection_calculator", "polars", pl.TopicDetectionCalculatorPolars)
    NlpStatisticsFactory.register("topic_detection_calculator", "spark", sp.TopicDetectionCalculatorSpark)
    NlpStatisticsFactory.register("stopword_filter", "pandas", p.StopwordFilterPandas)
    NlpStatisticsFactory.register("stopword_filter", "polars", pl.StopwordFilterPolars)
    NlpStatisticsFactory.register("stopword_filter", "spark", sp.StopwordFilterSpark)
    NlpStatisticsFactory.register("corpus_tokenizer", "pandas", p.CorpusTokenizerPandas)
    NlpStatisticsFactory.register("corpus_tokenizer", "polars", pl.CorpusTokenizerPolars)
    NlpStatisticsFactory.register("corpus_tokenizer", "spark", sp.CorpusTokenizerSpark)
    NlpStatisticsFactory.register("tf_calculator", "pandas", p.TFCalculatorPandas)
    NlpStatisticsFactory.register("tf_calculator", "polars", pl.TFCalculatorPolars)
    NlpStatisticsFactory.register("tf_calculator", "spark", sp.TFCalculatorSpark)
    NlpStatisticsFactory.register("idf_calculator", "pandas", p.IDFCalculatorPandas)
    NlpStatisticsFactory.register("idf_calculator", "polars", pl.IDFCalculatorPolars)
    NlpStatisticsFactory.register("idf_calculator", "spark", sp.IDFCalculatorSpark)
    NlpStatisticsFactory.register("tfidf_aggregator", "pandas", p.TFIDFAggregatorPandas)
    NlpStatisticsFactory.register("tfidf_aggregator", "polars", pl.TFIDFAggregatorPolars)
    NlpStatisticsFactory.register("tfidf_aggregator", "spark", sp.TFIDFAggregatorSpark)
    NlpStatisticsFactory.register("word_frequency_calculator", "pandas", p.WordFrequencyCalculatorPandas)
    NlpStatisticsFactory.register("word_frequency_calculator", "polars", pl.WordFrequencyCalculatorPolars)
    NlpStatisticsFactory.register("word_frequency_calculator", "spark", sp.WordFrequencyCalculatorSpark)

_register()
