from typing import Any
from database.postgres_manager import PostgresManager

class PostgresAdminAgent:
    """Agent responsible for persisting cleaned and analyzed data into PostgreSQL."""
    
    def __init__(self, backend: str):
        self.backend = backend
        self.db_manager = PostgresManager()
        
    def execute_persistence(self, data: Any, table_name: str, schema_instructions: str = ""):
        """
        Orchestrates the persistence of data to PostgreSQL.
        
        Args:
            data: The backend-specific dataframe.
            table_name: The target table name.
            schema_instructions: Optional instructions for the schema, which 
                                 could be generated by the LLM ContextCreatorAgent.
        """
        print(f"[PostgresAdminAgent] Preparing to save data to '{table_name}' using {self.backend} backend...")
        
        # Here we could theoretically ask an LLM to generate DDL based on `schema_instructions`
        # and execute it using `self.db_manager.execute_query(ddl_query)`.
        # For simplicity, we just rely on the native data frame writers which can auto-create the table.
        
        try:
            self.db_manager.write_dataframe(data, table_name, self.backend, if_exists="replace")
            print(f"[PostgresAdminAgent] Successfully saved data to '{table_name}'.")
            return {"status": "success", "table": table_name}
        except Exception as e:
            print(f"[PostgresAdminAgent] Error saving data: {e}")
            return {"status": "error", "message": str(e)}
